-- MySQL Script generated by MySQL Workbench
-- недеља, 20. децембар 2020. 12:28:13 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
DROP SCHEMA IF EXISTS mydb;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `id_Director` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(20) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Director`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studio` (
  `id_Studio` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Headquarters` VARCHAR(20) NOT NULL,
  `Founded` INT NOT NULL,
  PRIMARY KEY (`id_Studio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employed` (
  `Director_id_Director` INT NOT NULL,
  `Salary` INT NOT NULL,
  `Studio_id_Studio` INT NOT NULL,
  PRIMARY KEY (`Director_id_Director`),
  INDEX `fk_Employed_Studio1_idx` (`Studio_id_Studio` ASC),
  CONSTRAINT `fk_Employed_Director1`
    FOREIGN KEY (`Director_id_Director`)
    REFERENCES `mydb`.`Director` (`id_Director`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Employed_Studio1`
    FOREIGN KEY (`Studio_id_Studio`)
    REFERENCES `mydb`.`Studio` (`id_Studio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `id_Movie` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `Filming_start` DATE NOT NULL,
  `Filming_end` DATE NOT NULL,
  `Director_id_Director` INT NOT NULL,
  PRIMARY KEY (`id_Movie`),
  INDEX `fk_Movie_Director1_idx` (`Director_id_Director` ASC),
  CONSTRAINT `fk_Movie_Director1`
    FOREIGN KEY (`Director_id_Director`)
    REFERENCES `mydb`.`Director` (`id_Director`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `id_Actor` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Actor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acting_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acting_job` (
  `Movie_id_Movie` INT NOT NULL,
  `Actor_id_Actor` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Contract` INT NOT NULL,
  PRIMARY KEY (`Movie_id_Movie`, `Actor_id_Actor`),
  INDEX `fk_Acting_job_Actor1_idx` (`Actor_id_Actor` ASC),
  CONSTRAINT `fk_Acting_job_Movie1`
    FOREIGN KEY (`Movie_id_Movie`)
    REFERENCES `mydb`.`Movie` (`id_Movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Acting_job_Actor1`
    FOREIGN KEY (`Actor_id_Actor`)
    REFERENCES `mydb`.`Actor` (`id_Actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cover` (
  `Actor_id_Actor_1` INT NOT NULL,
  `Actor_id_Actor_2` INT NOT NULL,
  PRIMARY KEY (`Actor_id_Actor_1`, `Actor_id_Actor_2`),
  INDEX `fk_Cover_Actor2_idx` (`Actor_id_Actor_2` ASC),
  CONSTRAINT `fk_Cover_Actor1`
    FOREIGN KEY (`Actor_id_Actor_1`)
    REFERENCES `mydb`.`Actor` (`id_Actor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cover_Actor2`
    FOREIGN KEY (`Actor_id_Actor_2`)
    REFERENCES `mydb`.`Actor` (`id_Actor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenography`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenography` (
  `Serial_Number` INT NOT NULL,
  `Movie_id_Movie` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Serial_Number`, `Movie_id_Movie`),
  INDEX `fk_Scenography_Movie1_idx` (`Movie_id_Movie` ASC),
  CONSTRAINT `fk_Scenography_Movie1`
    FOREIGN KEY (`Movie_id_Movie`)
    REFERENCES `mydb`.`Movie` (`id_Movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producing` (
  `Movie_id_Movie` INT NOT NULL,
  `Studio_id_Studio` INT NOT NULL,
  `Budget` INT NOT NULL,
  INDEX `fk_Producing_Studio1_idx` (`Studio_id_Studio` ASC),
  PRIMARY KEY (`Movie_id_Movie`),
  CONSTRAINT `fk_Producing_Studio1`
    FOREIGN KEY (`Studio_id_Studio`)
    REFERENCES `mydb`.`Studio` (`id_Studio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producing_Movie1`
    FOREIGN KEY (`Movie_id_Movie`)
    REFERENCES `mydb`.`Movie` (`id_Movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
